In [228]:
import pandas as pd
import numpy as np
from data import * 
from inputs import *
from expenses import * 
from revenues import *

# Expenses

In [229]:
debt_service_exp = debt_service_df.loc["Total"]
corp_exp = corp_df.loc[("Total", "")]
op_exp = op_df.loc[("Total", "")]

In [230]:
summ_df = pd.DataFrame([corp_exp, op_exp, debt_service_exp, ], index=["Corporate Expenses", "Operations Expenses", "Debt Service"])
summ_df

,Financial Close - July 2023,Construction Year 1 - July 2024,Commisioning and Construction Year 2 - July 2025,July 2026 - Year 1,July 2027 - Year 2,July 2028 - Year 3,July 2029 - Year 4,July 2030 - Year 5,July 2031 - Year 6,July 2032 - Year 7,...,July 2056 - Year 31,July 2057 - Year 32,July 2058 - Year 33,July 2059 - Year 34,July 2060 - Year 35,July 2061 - Year 36,July 2062 - Year 37,July 2063 - Year 38,July 2064 - Year 39,July 2065 - Year 40
Corporate Expenses,0.0,9602000.0,9842050.0,10088101.25,1.034030e+07,1.059881e+07,1.086378e+07,1.113538e+07,1.141376e+07,1.169910e+07,...,2.116047e+07,2.168949e+07,2.223172e+07,2.278752e+07,2.335720e+07,2.394113e+07,2.453966e+07,2.515315e+07,2.578198e+07,2.642653e+07
Operations Expenses,0.0,0.0,9700000.0,3000000.00,3.000000e+06,3.000000e+06,3.000000e+06,3.000000e+06,3.000000e+06,3.000000e+06,...,3.110000e+06,3.110000e+06,3.110000e+06,3.110000e+06,3.110000e+06,3.110000e+06,3.110000e+06,3.110000e+06,3.110000e+06,3.110000e+06
Debt Service,0.0,0.0,16800000.0,50257935.00,4.599618e+07,5.128977e+07,4.643717e+07,5.139537e+07,4.744503e+07,5.093294e+07,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00

In [231]:
# summarize construction costs 
year_1 = const_df.iloc[const_df.index.get_level_values(0)=="Total", 2:14].sum(axis=1).values[0]

year_2 = const_df.iloc[const_df.index.get_level_values(0)=="Total", 14:].sum(axis=1).values[0]

by_fc = const_df.iloc[const_df.index.get_level_values(0)=="Total", 0:2].sum(axis=1).values[0]
year_1

317503000.0

In [232]:
const_costs = len(summ_df.columns)*[0]
const_costs[0] = by_fc
const_costs[1] = year_1
const_costs[2] = year_2
const_exp = pd.DataFrame(const_costs, index=list(summ_df.columns), columns=["Construction Expenses"]).T

In [233]:
summary_df = pd.concat(objs=[const_exp, summ_df])

In [234]:
hipu_escrow_op = 22.5e6
hipu_escrow_fc = 7e6

hipu_escrow = [0]* len(year_nums)
hipu_escrow[0] = hipu_escrow_op
annual_escrow_dec = 0.05

for i in year_nums[0:-1]:
    hipu_escrow[i] = hipu_escrow[i-1]*(1-annual_escrow_dec)

hipu_escrow_full = [hipu_escrow_fc, hipu_escrow_fc, hipu_escrow_fc] + hipu_escrow

In [235]:
summary_df.loc["HIPU Escrow*"] = hipu_escrow_full

In [236]:
summary_df.loc["Total Expenses"] = summary_df.sum(axis=0)

# Net Income

In [238]:
summary_df.loc["Revenues"] = rev_df.loc["Total"].T # TODO expenses should be negative!

In [239]:
summary_df.loc["Net Income"] = summary_df.loc["Revenues"] - summary_df.loc["Total Expenses"]

In [240]:
summary_df

,Financial Close - July 2023,Construction Year 1 - July 2024,Commisioning and Construction Year 2 - July 2025,July 2026 - Year 1,July 2027 - Year 2,July 2028 - Year 3,July 2029 - Year 4,July 2030 - Year 5,July 2031 - Year 6,July 2032 - Year 7,...,July 2056 - Year 31,July 2057 - Year 32,July 2058 - Year 33,July 2059 - Year 34,July 2060 - Year 35,July 2061 - Year 36,July 2062 - Year 37,July 2063 - Year 38,July 2064 - Year 39,July 2065 - Year 40
Construction Expenses,104646000.0,317503000.0,317503000.0,0.00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
Corporate Expenses,0.0,9602000.0,9842050.0,10088101.25,1.034030e+07,1.059881e+07,1.086378e+07,1.113538e+07,1.141376e+07,1.169910e+07,...,2.116047e+07,2.168949e+07,2.223172e+07,2.278752e+07,2.335720e+07,2.394113e+07,2.453966e+07,2.515315e+07,2.578198e+07,2.642653e+07
Operations Expenses,0.0,0.0,9700000.0,3000000.00,3.000000e+06,3.000000e+06,3.000000e+06,3.000000e+06,3.000000e+06,3.000000e+06,...,3.110000e+06,3.110000e+06,3.110000e+06,3.110000e+06,3.110000e+06,3.110000e+06,3.110000e+06,3.110000e+06,3.110000e+06,3.110000e+06
Debt Service,0.0,0.0,16800000.0,50257935.00,4.599618e+07,5.128977e+07,4.643717e+07,5.139537e+07,4.744503e+07,5.093294e+07,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
HIPU Escrow*,7000000.0,7000000.0,7000000.0,22500000.00,2.137500e+07,2.030625e+07,1.929094e+07,1.832639e+07,1.741007e+07,1.653957e+07,...,4.829372e+06,4.587904e+06,4.358508e+06,4.140583e+06,3.933554e+06,3.736876e+06,3.550032e+06,3.372531e+06,3.203904e+06,3.043709e+06
Total Expenses,111646000.0,334105000.0,360845050.0,85846036.25,8.071148e+07,8.519483e+07,7.959189e+07,8.385713e+07,7.926886e+07,8.217162e+07,...,2.909985e+07,2.938739e+07,2.970023e+07,3.003810e+07,3.040076e+07,3.078801e+07,3.119969e+07,3.163568e+07,3.209589e+07,3.258024e+07
Revenues,550062792.0,0.0,0.0,80541120.00,8.456818e+07,8.879658e+07,9.323641e+07,9.789823e+07,1.027931e+08,1.079328e+08,...,3.480941e+08,3.654988e+08,3.837737e+08,4.029624e+08,4.231105e+08,4.442661e+08,4.664794e+08,4.898033e+08,5.142935e+08,5.400082e+08
Net Income,438416792.0,-334105000.0,-360845050.0,-5304916.25,3.856693e+06,3.601753e+06,1.364453e+07,1.404110e+07,2.352428e+07,2.576119e+07,...,3.189942e+08,3.361114e+08,3.540735e+08,3.729243e+08,3.927098e+08,4.134780e+08,4.352797e+08,4.581676e+08,4.821976e+08,5.074279e+08

# Taxes

In [246]:
# corporate taxes => 30% of net income
summary_df.loc["Corporate Tax Payable"] = summary_df.loc["Net Income"]*0.3

In [249]:
summary_df.iloc[-1, 0:4] = 0

In [250]:
summary_df

,Financial Close - July 2023,Construction Year 1 - July 2024,Commisioning and Construction Year 2 - July 2025,July 2026 - Year 1,July 2027 - Year 2,July 2028 - Year 3,July 2029 - Year 4,July 2030 - Year 5,July 2031 - Year 6,July 2032 - Year 7,...,July 2056 - Year 31,July 2057 - Year 32,July 2058 - Year 33,July 2059 - Year 34,July 2060 - Year 35,July 2061 - Year 36,July 2062 - Year 37,July 2063 - Year 38,July 2064 - Year 39,July 2065 - Year 40
Construction Expenses,104646000.0,317503000.0,317503000.0,0.00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
Corporate Expenses,0.0,9602000.0,9842050.0,10088101.25,1.034030e+07,1.059881e+07,1.086378e+07,1.113538e+07,1.141376e+07,1.169910e+07,...,2.116047e+07,2.168949e+07,2.223172e+07,2.278752e+07,2.335720e+07,2.394113e+07,2.453966e+07,2.515315e+07,2.578198e+07,2.642653e+07
Operations Expenses,0.0,0.0,9700000.0,3000000.00,3.000000e+06,3.000000e+06,3.000000e+06,3.000000e+06,3.000000e+06,3.000000e+06,...,3.110000e+06,3.110000e+06,3.110000e+06,3.110000e+06,3.110000e+06,3.110000e+06,3.110000e+06,3.110000e+06,3.110000e+06,3.110000e+06
Debt Service,0.0,0.0,16800000.0,50257935.00,4.599618e+07,5.128977e+07,4.643717e+07,5.139537e+07,4.744503e+07,5.093294e+07,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
HIPU Escrow*,7000000.0,7000000.0,7000000.0,22500000.00,2.137500e+07,2.030625e+07,1.929094e+07,1.832639e+07,1.741007e+07,1.653957e+07,...,4.829372e+06,4.587904e+06,4.358508e+06,4.140583e+06,3.933554e+06,3.736876e+06,3.550032e+06,3.372531e+06,3.203904e+06,3.043709e+06
Total Expenses,111646000.0,334105000.0,360845050.0,85846036.25,8.071148e+07,8.519483e+07,7.959189e+07,8.385713e+07,7.926886e+07,8.217162e+07,...,2.909985e+07,2.938739e+07,2.970023e+07,3.003810e+07,3.040076e+07,3.078801e+07,3.119969e+07,3.163568e+07,3.209589e+07,3.258024e+07
Revenues,550062792.0,0.0,0.0,80541120.00,8.456818e+07,8.879658e+07,9.323641e+07,9.789823e+07,1.027931e+08,1.079328e+08,...,3.480941e+08,3.654988e+08,3.837737e+08,4.029624e+08,4.231105e+08,4.442661e+08,4.664794e+08,4.898033e+08,5.142935e+08,5.400082e+08
Net Income,438416792.0,-334105000.0,-360845050.0,-5304916.25,3.856693e+06,3.601753e+06,1.364453e+07,1.404110e+07,2.352428e+07,2.576119e+07,...,3.189942e+08,3.361114e+08,3.540735e+08,3.729243e+08,3.927098e+08,4.134780e+08,4.352797e+08,4.581676e+08,4.821976e+08,5.074279e+08
Corporate Tax Payable,0.0,0.0,0.0,0.00,1.157008e+06,1.080526e+06,4.093358e+06,4.212331e+06,7.057285e+06,7.728356e+06,...,9.569827e+07,1.008334e+08,1.062220e+08,1.118773e+08,1.178129e+08,1.240434e+08,1.305839e+08,1.374503e+08,1.446593e+08,1.522284e+08

In [251]:
summary_df.loc["After Tax Income"] = summary_df.loc["Net Income"] - summary_df.loc["Corporate Tax Payable"]

In [252]:
summary_df

,Financial Close - July 2023,Construction Year 1 - July 2024,Commisioning and Construction Year 2 - July 2025,July 2026 - Year 1,July 2027 - Year 2,July 2028 - Year 3,July 2029 - Year 4,July 2030 - Year 5,July 2031 - Year 6,July 2032 - Year 7,...,July 2056 - Year 31,July 2057 - Year 32,July 2058 - Year 33,July 2059 - Year 34,July 2060 - Year 35,July 2061 - Year 36,July 2062 - Year 37,July 2063 - Year 38,July 2064 - Year 39,July 2065 - Year 40
Construction Expenses,104646000.0,317503000.0,317503000.0,0.00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
Corporate Expenses,0.0,9602000.0,9842050.0,10088101.25,1.034030e+07,1.059881e+07,1.086378e+07,1.113538e+07,1.141376e+07,1.169910e+07,...,2.116047e+07,2.168949e+07,2.223172e+07,2.278752e+07,2.335720e+07,2.394113e+07,2.453966e+07,2.515315e+07,2.578198e+07,2.642653e+07
Operations Expenses,0.0,0.0,9700000.0,3000000.00,3.000000e+06,3.000000e+06,3.000000e+06,3.000000e+06,3.000000e+06,3.000000e+06,...,3.110000e+06,3.110000e+06,3.110000e+06,3.110000e+06,3.110000e+06,3.110000e+06,3.110000e+06,3.110000e+06,3.110000e+06,3.110000e+06
Debt Service,0.0,0.0,16800000.0,50257935.00,4.599618e+07,5.128977e+07,4.643717e+07,5.139537e+07,4.744503e+07,5.093294e+07,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
HIPU Escrow*,7000000.0,7000000.0,7000000.0,22500000.00,2.137500e+07,2.030625e+07,1.929094e+07,1.832639e+07,1.741007e+07,1.653957e+07,...,4.829372e+06,4.587904e+06,4.358508e+06,4.140583e+06,3.933554e+06,3.736876e+06,3.550032e+06,3.372531e+06,3.203904e+06,3.043709e+06
Total Expenses,111646000.0,334105000.0,360845050.0,85846036.25,8.071148e+07,8.519483e+07,7.959189e+07,8.385713e+07,7.926886e+07,8.217162e+07,...,2.909985e+07,2.938739e+07,2.970023e+07,3.003810e+07,3.040076e+07,3.078801e+07,3.119969e+07,3.163568e+07,3.209589e+07,3.258024e+07
Revenues,550062792.0,0.0,0.0,80541120.00,8.456818e+07,8.879658e+07,9.323641e+07,9.789823e+07,1.027931e+08,1.079328e+08,...,3.480941e+08,3.654988e+08,3.837737e+08,4.029624e+08,4.231105e+08,4.442661e+08,4.664794e+08,4.898033e+08,5.142935e+08,5.400082e+08
Net Income,438416792.0,-334105000.0,-360845050.0,-5304916.25,3.856693e+06,3.601753e+06,1.364453e+07,1.404110e+07,2.352428e+07,2.576119e+07,...,3.189942e+08,3.361114e+08,3.540735e+08,3.729243e+08,3.927098e+08,4.134780e+08,4.352797e+08,4.581676e+08,4.821976e+08,5.074279e+08
Corporate Tax Payable,0.0,0.0,0.0,0.00,1.157008e+06,1.080526e+06,4.093358e+06,4.212331e+06,7.057285e+06,7.728356e+06,...,9.569827e+07,1.008334e+08,1.062220e+08,1.118773e+08,1.178129e+08,1.240434e+08,1.305839e+08,1.374503e+08,1.446593e+08,1.522284e+08
After Tax Income,438416792.0,-334105000.0,-360845050.0,-5304916.25,2.699685e+06,2.521227e+06,9.551168e+06,9.828771e+06,1.646700e+07,1.803283e+07,...,2.232960e+08,2.352780e+08,2.478514e+08,2.610470e+08,2.748968e+08,2.894346e+08,3.046958e+08,3.207173e+08,3.375383e+08,3.551995e+08