In [159]:
import pandas as pd
import numpy as np
from data import * 
from inputs import *
from expenses import * 
from revenues import *

# Expenses

In [174]:
debt_service_exp = debt_service_df.loc["Total"]
corp_exp = corp_df.loc[("Total", "")]
op_exp = op_df.loc[("Total", "")]

In [162]:
summ_df = pd.DataFrame([corp_exp, op_exp, debt_service_exp, ], index=["Corporate Expenses", "Operations Expenses", "Debt Service"])
summ_df

,Financial Close - July 2023,Construction Year 1 - July 2024,Commisioning and Construction Year 2 - July 2025,July 2026 - Year 1,July 2027 - Year 2,July 2028 - Year 3,July 2029 - Year 4,July 2030 - Year 5,July 2031 - Year 6,July 2032 - Year 7,...,July 2056 - Year 31,July 2057 - Year 32,July 2058 - Year 33,July 2059 - Year 34,July 2060 - Year 35,July 2061 - Year 36,July 2062 - Year 37,July 2063 - Year 38,July 2064 - Year 39,July 2065 - Year 40
Corporate Expenses,0.0,9602000.0,9842050.0,10088101.25,1.034030e+07,1.059881e+07,1.086378e+07,1.113538e+07,1.141376e+07,1.169910e+07,...,2.116047e+07,2.168949e+07,2.223172e+07,2.278752e+07,2.335720e+07,2.394113e+07,2.453966e+07,2.515315e+07,2.578198e+07,2.642653e+07
Operations Expenses,0.0,0.0,9700000.0,3000000.00,3.000000e+06,3.000000e+06,3.000000e+06,3.000000e+06,3.000000e+06,3.000000e+06,...,3.110000e+06,3.110000e+06,3.110000e+06,3.110000e+06,3.110000e+06,3.110000e+06,3.110000e+06,3.110000e+06,3.110000e+06,3.110000e+06
Debt Service,0.0,0.0,16800000.0,50257935.00,4.599618e+07,5.128977e+07,4.643717e+07,5.139537e+07,4.744503e+07,5.093294e+07,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00

In [164]:
# summarize construction costs 
year_1 = const_df.iloc[const_df.index.get_level_values(0)=="Total", 2:14].sum(axis=1).values[0]

year_2 = const_df.iloc[const_df.index.get_level_values(0)=="Total", 14:].sum(axis=1).values[0]

by_fc = const_df.iloc[const_df.index.get_level_values(0)=="Total", 0:2].sum(axis=1).values[0]
year_1

317503000.0

In [165]:
const_costs = len(summ_df.columns)*[0]
const_costs[0] = by_fc
const_costs[1] = year_1
const_costs[2] = year_2
const_exp = pd.DataFrame(const_costs, index=list(summ_df.columns), columns=["Construction Expenses"]).T

In [166]:
summ_df2 = pd.concat(objs=[const_exp, summ_df])

In [168]:
summ_df2.loc["Total Expenses"] = summ_df2.sum(axis=0)

# Revenues

In [170]:
summ_df2.loc["Revenues"] = rev_df.loc["Total"].T # TODO expenses should be negative!

In [172]:
summ_df2.loc["EBITDA and Holdings"] = summ_df2.loc["Revenues"] - summ_df2.loc["Total Expenses"]

In [173]:
summ_df2

,Financial Close - July 2023,Construction Year 1 - July 2024,Commisioning and Construction Year 2 - July 2025,July 2026 - Year 1,July 2027 - Year 2,July 2028 - Year 3,July 2029 - Year 4,July 2030 - Year 5,July 2031 - Year 6,July 2032 - Year 7,...,July 2056 - Year 31,July 2057 - Year 32,July 2058 - Year 33,July 2059 - Year 34,July 2060 - Year 35,July 2061 - Year 36,July 2062 - Year 37,July 2063 - Year 38,July 2064 - Year 39,July 2065 - Year 40
Construction Expenses,104646000.0,317503000.0,317503000.0,0.00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
Corporate Expenses,0.0,9602000.0,9842050.0,10088101.25,1.034030e+07,1.059881e+07,1.086378e+07,1.113538e+07,1.141376e+07,1.169910e+07,...,2.116047e+07,2.168949e+07,2.223172e+07,2.278752e+07,2.335720e+07,2.394113e+07,2.453966e+07,2.515315e+07,2.578198e+07,2.642653e+07
Operations Expenses,0.0,0.0,9700000.0,3000000.00,3.000000e+06,3.000000e+06,3.000000e+06,3.000000e+06,3.000000e+06,3.000000e+06,...,3.110000e+06,3.110000e+06,3.110000e+06,3.110000e+06,3.110000e+06,3.110000e+06,3.110000e+06,3.110000e+06,3.110000e+06,3.110000e+06
Debt Service,0.0,0.0,16800000.0,50257935.00,4.599618e+07,5.128977e+07,4.643717e+07,5.139537e+07,4.744503e+07,5.093294e+07,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
Total Expenses,104646000.0,327105000.0,353845050.0,63346036.25,5.933648e+07,6.488858e+07,6.030095e+07,6.553074e+07,6.185879e+07,6.563205e+07,...,2.427047e+07,2.479949e+07,2.534172e+07,2.589752e+07,2.646720e+07,2.705113e+07,2.764966e+07,2.826315e+07,2.889198e+07,2.953653e+07
Revenues,550062792.0,0.0,0.0,80541120.00,8.456818e+07,8.879658e+07,9.323641e+07,9.789823e+07,1.027931e+08,1.079328e+08,...,3.480941e+08,3.654988e+08,3.837737e+08,4.029624e+08,4.231105e+08,4.442661e+08,4.664794e+08,4.898033e+08,5.142935e+08,5.400082e+08
EBITDA and Holdings,445416792.0,-327105000.0,-353845050.0,17195083.75,2.523169e+07,2.390800e+07,3.293546e+07,3.236749e+07,4.093435e+07,4.230076e+07,...,3.238236e+08,3.406993e+08,3.584320e+08,3.770649e+08,3.966433e+08,4.172149e+08,4.388297e+08,4.615402e+08,4.854015e+08,5.104716e+08

In [ ]:
# TODO -> holdings, coprorate taxes, depreciation of assets